version: '3.7'

services:
  symfony:
    image: cocoders/phpers-summit-2019-symfony
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/www/beer-menu/key/key.json
      - VIRTUAL_HOST=beer.local
      - VIRTUAL_PORT=8000
    expose:
      - "8000"
    volumes:
      - ./symfony/:/var/www/beer
    networks:
      - default
      - nginx-proxy
    command: >
      bash -c "symfony composer install && symfony server:start"

  angular:
    image: cocoders/phpers-summit-2019-angular
    volumes:
      - ./angular/:/var/www/beer
    networks:
      - default
      - nginx-proxy
    expose:
      - "4200"
    environment:
      - VIRTUAL_HOST=frontend.beer.local
      - VIRTUAL_PORT=4200
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --disable-host-check --public-host=frontend.beer.local"

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - default
      - nginx-proxy

  whoami:
    image: jwilder/whoami
    networks:
      - default
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
